import React, { useEffect } from 'react';
import { type LanguageCode } from '../content';

type PrivacyProps = {
  language: LanguageCode;
};

const Privacy: React.FC<PrivacyProps> = ({ language }) => {
  useEffect(() => {
    window.scrollTo(0, 0);
  }, []);

  // Simple placeholder content for privacy policy
  const content = {
    en: {
      title: 'Privacy Policy',
      lastUpdated: 'Last Updated: May 31, 2026',
      intro: 'At Zeus Anti-Cheat, we are committed to protecting your privacy and ensuring the security of your data. This Privacy Policy explains how we collect, use, and safeguard information when you use the Zeus Platform.',
      sections: [
        {
          title: '1. Information We Collect',
          content: 'We collect minimal telemetry data necessary for machine learning behavior analysis. This includes game-state information, network metrics, and generic behavior vectors. We DO NOT collect personal identification information from players.',
        },
        {
          title: '2. How We Use Information',
          content: 'Data collected by the Zeus Platform is strictly used for training our machine learning models, improving detection accuracy, and providing you with anomalous behavior reports. We do not sell or share your data with third parties.',
        },
        {
          title: '3. Data Security',
          content: 'All communication between the game servers and the Zeus backend is encrypted. Our databases are secured with industry-standard protocols, and access is strictly restricted to authorized administrators on your own network.',
        },
        {
          title: '4. Your Rights',
          content: 'As a self-hosted platform, you have complete control over your data. You may purge, modify, or export the datasets generated by your servers at any time.',
        }
      ]
    },
    vi: {
      title: 'Chính sách bảo mật',
      lastUpdated: 'Cập nhật lần cuối: 31 Tháng 5, 2026',
      intro: 'Tại Zeus Anti-Cheat, chúng tôi cam kết bảo vệ quyền riêng tư và đảm bảo an toàn cho dữ liệu của bạn. Chính sách này giải thích cách chúng tôi thu thập, sử dụng và bảo vệ thông tin khi bạn dùng Zeus Platform.',
      sections: [
        {
          title: '1. Thông tin thu thập',
          content: 'Chúng tôi thu thập dữ liệu telemetry tối thiểu cần thiết cho việc phân tích hành vi của máy học. Bao gồm thông tin trạng thái game, chỉ số mạng và các vector hành vi chung. Chúng tôi KHÔNG thu thập thông tin nhận dạng cá nhân của người chơi.',
        },
        {
          title: '2. Cách sử dụng thông tin',
          content: 'Dữ liệu thu thập bởi Zeus Platform chỉ được sử dụng nghiêm ngặt cho việc huấn luyện mô hình máy học, cải thiện độ chính xác phát hiện và cung cấp báo cáo hành vi bất thường. Chúng tôi không bán hay chia sẻ dữ liệu cho bên thứ ba.',
        },
        {
          title: '3. Bảo mật dữ liệu',
          content: 'Mọi giao tiếp giữa máy chủ game và Zeus backend đều được mã hóa. Cơ sở dữ liệu được bảo vệ bằng các giao thức chuẩn công nghiệp, và chỉ quản trị viên được ủy quyền mới có quyền truy cập.',
        },
        {
          title: '4. Quyền của bạn',
          content: 'Là nền tảng tự lưu trữ, bạn có toàn quyền kiểm soát dữ liệu của mình. Bạn có thể xóa, chỉnh sửa hoặc trích xuất các tập dữ liệu do máy chủ tạo ra bất kỳ lúc nào.',
        }
      ]
    }
  };

  const copy = content[language];

  return (
    <div className="max-w-[800px] mx-auto px-6 py-12 md:py-20">
      <h1 className="text-3xl md:text-4xl font-bold font-heading text-text-main mb-4 tracking-tight">{copy.title}</h1>
      <p className="text-text-sec text-sm mb-8">{copy.lastUpdated}</p>

      <div className="prose prose-invert max-w-none text-text-sec">
        <p className="text-[1.05rem] leading-relaxed mb-8">
          {copy.intro}
        </p>

        {copy.sections.map((section, index) => (
          <div key={index} className="mb-8">
            <h2 className="text-xl font-semibold text-text-main mb-3">{section.title}</h2>
            <p className="text-[1rem] leading-relaxed">{section.content}</p>
          </div>
        ))}

        <div className="mt-12 p-6 bg-white/5 border border-card-border rounded-lg">
          <p className="text-sm">
            {language === 'en'
              ? 'If you have any questions about this Privacy Policy, please refer to our documentation or contact support.'
              : 'Nếu bạn có câu hỏi về Chính sách bảo mật này, vui lòng tham khảo tài liệu hoặc liên hệ hỗ trợ.'}
          </p>
        </div>
      </div>
    </div>
  );
};

export default Privacy;